### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Extocine** [KoboldAI/KoboldAI-Client#451] opened 2024-08-21 20:42 UTC
Installed the game for the first time, and unable to start using either ./play.sh or ./play-rocm.sh
Specs:
Ryzen 5 5600
RX 5700-XT
32Gb DDR4 3200Mhz
Debian 12

``RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/media/extocine/3TB/ai/KoboldAI-Client/runtime/envs/koboldai/lib/python3.8/site-packages/huggingface_hub/__init__.py)``

**Comment by henk717** [comment] 2024-08-21 20:55
Duplicate of https://github.com/KoboldAI/KoboldAI-Client/issues/446
Its recommended to use our newer product https://koboldai.org/cpp instead

**Closed by henk717** 2024-08-21 20:55 UTC
